/**
 * Zero-dependency bundler for canvasxpress-dashboards.
 *
 * The source is authored as small ES modules under `src/`. This script inlines
 * them (in dependency order) into two distributable artifacts:
 *
 *   dist/canvasxpress-dashboards.esm.js  — ESM, named exports
 *   dist/canvasxpress-dashboards.umd.js  — UMD, global `CanvasXpressDashboards`
 *
 * It intentionally avoids a bundler toolchain: the module graph is small and
 * flat (no circular deps, only named exports), so inlining is a line transform.
 *
 * Run: `node scripts/build.mjs`
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

var here = dirname(fileURLToPath(import.meta.url));
var root = join(here, '..');
var srcDir = join(root, 'src');
var distDir = join(root, 'dist');

// Dependency order — leaves first, entry last-ish. index.js only re-exports.
var MODULES = ['styles.js', 'dataStore.js', 'validateSpec.js', 'renderDashboard.js', 'persistence.js', 'builderModel.js', 'builder.js'];

// Public API exposed by both bundles.
var EXPORTS = [
  'renderDashboard',
  'validateSpec',
  'dashboardCss',
  'injectStyles',
  'createDataStore',
  'isEmptyData',
  'DataError',
  'clearSharedCache',
  'exportSpec',
  'importSpecFromFile',
  'parseAndValidate',
  'createDashboardClient',
  'createBuilder',
  'pointerToCell',
  'addPanel',
  'removePanel',
  'movePanel',
  'resizePanel',
  'updatePanel',
  'setDataSource',
  'blankSpec',
  'DEFAULT_COLS'
];
var VERSION = readVersion();

/**
 * Strip ESM import/export syntax from a module body so it can be inlined.
 * @param {string} code - Raw module source.
 * @returns {string} Body with imports removed and `export ` prefixes dropped.
 */
function stripModule(code) {
  return code
    // Drop `import { ... } from './x.js';` lines (internal deps are inlined).
    .replace(/^\s*import\s+[^;]*;\s*$/gm, '')
    // Drop `export { ... } from '...';` re-export lines.
    .replace(/^\s*export\s+\{[^}]*\}\s+from\s+[^;]*;\s*$/gm, '')
    // Turn `export function foo` / `export var foo` into plain declarations.
    .replace(/^\s*export\s+(function|var|const|let|class)\b/gm, '$1');
}

var body = MODULES
  .map(function (name) {
    var code = readFileSync(join(srcDir, name), 'utf8');
    return '/* ==== src/' + name + ' ==== */\n' + stripModule(code).trim() + '\n';
  })
  .join('\n');

var apiObject =
  'var CanvasXpressDashboards = {\n' +
  EXPORTS.map(function (n) { return '  ' + n + ': ' + n; }).join(',\n') +
  ',\n  version: ' + JSON.stringify(VERSION) + '\n};';

mkdirSync(distDir, { recursive: true });

// --- ESM bundle ---
var esm =
  banner('ESM') +
  body +
  '\nvar version = ' + JSON.stringify(VERSION) + ';\n' +
  'export { ' + EXPORTS.join(', ') + ', version };\n' +
  'export default { ' + EXPORTS.join(', ') + ', version };\n';
writeFileSync(join(distDir, 'canvasxpress-dashboards.esm.js'), esm);

// --- UMD bundle ---
var umd =
  banner('UMD') +
  '(function (root, factory) {\n' +
  '  if (typeof define === "function" && define.amd) { define([], factory); }\n' +
  '  else if (typeof module === "object" && module.exports) { module.exports = factory(); }\n' +
  '  else { root.CanvasXpressDashboards = factory(); }\n' +
  '}(typeof self !== "undefined" ? self : this, function () {\n' +
  '"use strict";\n' +
  body + '\n' +
  apiObject + '\n' +
  'return CanvasXpressDashboards;\n' +
  '}));\n';
writeFileSync(join(distDir, 'canvasxpress-dashboards.umd.js'), umd);

// Mirror the UMD bundle into the server's static dir so the shared viewer is
// self-contained when served by cxd_server.
var serverStatic = join(root, 'server', 'src', 'cxd_server', 'static');
try {
  mkdirSync(serverStatic, { recursive: true });
  writeFileSync(join(serverStatic, 'canvasxpress-dashboards.umd.js'), umd);
} catch (e) {
  // Server package may be absent in a slim checkout — non-fatal.
}

console.log('Built dist/canvasxpress-dashboards.esm.js and .umd.js (v' + VERSION + ')');

/**
 * Read the package version from package.json.
 * @returns {string} The version string.
 */
function readVersion() {
  try {
    var pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
    return pkg.version || '0.0.0';
  } catch (e) {
    return '0.0.0';
  }
}

/**
 * Build a file banner comment.
 * @param {string} kind - Bundle kind label.
 * @returns {string} The banner text.
 */
function banner(kind) {
  return '/* canvasxpress-dashboards ' + VERSION + ' (' + kind + ') — generated by scripts/build.mjs. Do not edit. */\n';
}
